### ISSUE TITLE
License and UK release

### ISSUE THREAD

**Issue by rowleyaj** [promptworks/alexa-slack#6]
Hi @patricksmith,

I've been looking at creating something similar to this for the UK skills store and found your work here, however I noted that this repo has no license. Would you consider adding one?

Subject to a suitable license being added I'd then like to see if I could get this running on the UK store.

Thanks, Alex

**Comment by patricksmith** [comment]
Hi Alex,

I've added an MIT license to the repo, so feel free to take this code and modify how you see fit. 

Good luck getting it on the UK store and I'd be curious to hear about your experiences using this repo and [`pylexa`](https://github.com/patricksmith/pylexa)!
